[tool.black]
line-length = 100
target-version = ['py310']

[tool.isort]
py_version = 310
profile = "black"

[tool.pydocstyle]
convention = "numpy"

[tool.mypy]
python_version = "3.10"
allow_untyped_globals = true
follow_imports = "silent"

[[tool.mypy.overrides]]
module = [
	'setuptools.*',
]
ignore_missing_imports = true

[tool.pytest]
mock_use_standalone_module = true

[tool.pytest.ini_options]
minversion = "6.0"
#addopts = "-n auto"
pythonpath = [
  "."
]
python_files = "tests.py test_*.py tests_*.py"
required_plugins = "pytest-mock pytest-cov pytest-memray"

